variable "prefix" {}
variable "desired_count" {}
variable "cpu" {}
variable "memory_reservation" {}
variable "region" {}
variable "cluster_arn" {}
variable "log_destination_arn" {}
variable "docker_image" {}
variable "volumes" {}
variable "enable_cw_logging" {}
variable "get_dmrpp_timeout" {}